# 2025/06/13 perplexity Essential PEP 8 Std python code 
# https://www.perplexity.ai/search/set-up-pritter-codebase-Hzss.LUvSWeu2vTc2AG5Xg 
[tool.ruff]
line-length = 79
indent-width = 4
target-version = "py38"

[tool.ruff.lint]
select = [
  "E",   # pycodestyle errors
  "F",   # Pyflakes
  "W",   # pycodestyle warnings
  "I",   # isort (import sorting)
  "N",   # pep8-naming
  "B",   # flake8-bugbear
]
ignore = ["E501"]  # Let formatter handle line length

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
